name: "Audit monitoring/otelinit"

on:
  push:
    paths:
      - 'monitoring/otelinit/**'
      - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'monitoring/otelinit/**'
      - '.github/workflows/**'
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: monitoring/otelinit
          version: v1.46
          args: --config=./.golangci.toml
  sec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3               
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'    
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3  
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        working-directory: monitoring/otelinit
        run: |
          go test ./... -bench=. -benchmem | tee ./bench-continuous.txt
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache/monitoring/otelinit
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: ./monitoring/otelinit/bench-continuous.txt
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true         
          benchmark-data-dir-path: ./monitoring/otelinit/
          # When cache is used
          # external-data-json-path: ./cache/monitoring/otelinit/benchmark-data.json
          # Push and deploy GitHub pages branch automatically
          auto-push: true 