name: "Bench transport/http/middleware/cryptouseruuid"

on:
  push:
    paths:
      - 'transport/http/middleware/cryptouseruuid/**'
      - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'transport/http/middleware/cryptouseruuid/**'
      - '.github/workflows/**'
    branches: [ main ]

jobs: 
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3  
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        working-directory: transport/http/middleware/cryptouseruuid
        run: |
          go test ./... -bench=. -benchmem | tee ./bench-continuous.txt
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache/transport/http/middleware/cryptouseruuid
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: ./transport/http/middleware/cryptouseruuid/bench-continuous.txt
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true         
          benchmark-data-dir-path: ./transport/http/middleware/cryptouseruuid/
          # When cache is used
          # external-data-json-path: ./cache/transport/http/middleware/cryptouseruuid/benchmark-data.json    
          # Push and deploy GitHub pages branch automatically
          auto-push: true                 